
# Repo: codefoco/AzureDevopsTemplates
resources:
  repositories:
    - repository: templates
      type: github
      name: codefoco/AzureDevopsTemplates
      endpoint: codefoco

pool:
  vmImage: 'windows-2019'
  demands:
  - msbuild
  - visualstudio
  - vstest

steps:
- template: common-dotnet.yml@templates
- template: common-macos.yml@templates

- task: PowerShell@2
  displayName: 'PreBuild Script'
  inputs:
    targetType: filePath
    filePath: ./devops/PreBuild.ps1
    arguments: 'Codefoco.Touch.Server Codefoco.Touch.Server.nuspec'
    errorActionPreference: 'silentlyContinue'
    pwsh: true

- task: MSBuild@1
  displayName: 'Build solution Touch.Server.sln'
  inputs:
    solution: 'Touch.Server.sln'
    configuration: Release

- script: 'nuget setapikey $(apikey)'
  displayName: 'Set NuGet API Key'

- task: PowerShell@2
  displayName: 'Package NuGet'
  inputs:
    targetType: filePath
    filePath: ./devops/Package.ps1
    arguments: 'Codefoco.Touch.Server Codefoco.Touch.Server.nuspec'

- script: 'rename *.nupkg Codefoco.Touch.Server.nupkg'
  displayName: 'Rename Nuget Package'

- task: PublishBuildArtifacts@1
  displayName: 'Save Codefoco.Touch.Server.nupkg Artifact'
  inputs:
    PathtoPublish: Codefoco.Touch.Server.nupkg
    ArtifactName: Codefoco.Touch.Server.nupkg

- task: PowerShell@2
  displayName: 'Publish NuGet'
  inputs:
    targetType: filePath
    filePath: ./devops/Publish.ps1
    arguments: Codefoco.Touch.Server

- template: send-telegram.yml@templates